/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aglar_proje;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author emreu
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
        setTitle("Kullanıcı Giriş Ekranı");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGiris = new javax.swing.JPanel();
        lblSifre = new javax.swing.JLabel();
        lblKullaniciId = new javax.swing.JLabel();
        txtKullaniciId = new javax.swing.JTextField();
        txtSifre = new javax.swing.JTextField();
        btnKullaniciEkle = new javax.swing.JLabel();
        lblLoginResim = new javax.swing.JLabel();
        lblEkleResim = new javax.swing.JLabel();
        lblSifreDurum = new javax.swing.JLabel();
        btnPersonelEkle = new javax.swing.JButton();
        btnGiris = new javax.swing.JButton();
        lblidDurum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelGiris.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblSifre.setText("Şifre");

        lblKullaniciId.setText("Kullanıcı Id:");

        txtSifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSifreActionPerformed(evt);
            }
        });

        btnKullaniciEkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aglar_proje/urunresimleri/kullanicigiris.jpg"))); // NOI18N

        lblLoginResim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aglar_proje/urunresimleri/login_icon_1.png"))); // NOI18N

        lblEkleResim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aglar_proje/urunresimleri/uye_ol.png"))); // NOI18N

        btnPersonelEkle.setText("Kullanıcı Ekle");
        btnPersonelEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonelEkleActionPerformed(evt);
            }
        });

        btnGiris.setText("Giris");
        btnGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelGirisLayout = new javax.swing.GroupLayout(PanelGiris);
        PanelGiris.setLayout(PanelGirisLayout);
        PanelGirisLayout.setHorizontalGroup(
            PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGirisLayout.createSequentialGroup()
                .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelGirisLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(PanelGirisLayout.createSequentialGroup()
                                .addComponent(btnGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPersonelEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelGirisLayout.createSequentialGroup()
                                .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblSifre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblKullaniciId, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelGirisLayout.createSequentialGroup()
                                        .addComponent(txtKullaniciId, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(lblLoginResim))
                                    .addGroup(PanelGirisLayout.createSequentialGroup()
                                        .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblEkleResim)))))
                        .addGap(35, 35, 35)
                        .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblidDurum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSifreDurum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PanelGirisLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnKullaniciEkle)))
                .addGap(25, 25, 25))
        );
        PanelGirisLayout.setVerticalGroup(
            PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGirisLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnKullaniciEkle)
                .addGap(22, 22, 22)
                .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtKullaniciId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblKullaniciId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelGirisLayout.createSequentialGroup()
                            .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblLoginResim)
                                .addComponent(lblidDurum, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblEkleResim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSifreDurum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPersonelEkle)
                    .addComponent(btnGiris))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelGiris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(PanelGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonelEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonelEkleActionPerformed
        // TODO add your handling code here:
        PanelGiris.setVisible(false);
    }//GEN-LAST:event_btnPersonelEkleActionPerformed

    private void btnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisActionPerformed

        try {
            // TODO add your handling code here:
            Pattern idDesen = Pattern.compile("[0-9]");
            Pattern sifreDesen = Pattern.compile("[0-9]");
            Matcher idYakala = idDesen.matcher(txtKullaniciId.getText());
            Matcher sifreYakala = sifreDesen.matcher(txtSifre.getText());
            if (!idYakala.find()) {

                lblidDurum.setText("Kullanıcı id bulunmamaktadır.");

            } else {
                lblidDurum.setText("");
            }
            if (!sifreYakala.find()) {

                lblSifreDurum.setText("Şifre yanlış girilmiştir.");

            } else {
                lblSifreDurum.setText("");
            }
            String gelenId="1234";
            String gelenSifre= "1234";
            if (gelenId.equals(txtKullaniciId.getText()) && gelenSifre.equals(txtSifre.getText())) {
                MuzayedeEkrani ft = new MuzayedeEkrani();

                ft.setVisible(true);
                this.dispose();

            } else /*if(txtTc.getText()==" " && txtPersonelNo.getText()==" ")*/ {
                JOptionPane.showMessageDialog(this, "Bilgiler Doğru Girilmemiştir..");
            }

        } catch(Exception e){
            Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnGirisActionPerformed

    private void txtSifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSifreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSifreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelGiris;
    private javax.swing.JButton btnGiris;
    private javax.swing.JLabel btnKullaniciEkle;
    private javax.swing.JButton btnPersonelEkle;
    private javax.swing.JLabel lblEkleResim;
    private javax.swing.JLabel lblKullaniciId;
    private javax.swing.JLabel lblLoginResim;
    private javax.swing.JLabel lblSifre;
    private javax.swing.JLabel lblSifreDurum;
    private javax.swing.JLabel lblidDurum;
    private javax.swing.JTextField txtKullaniciId;
    private javax.swing.JTextField txtSifre;
    // End of variables declaration//GEN-END:variables
}
